# Generated by Django 2.2.4 on 2019-10-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='file',
        ),
    ]
