# Generated by Django 2.2.4 on 2019-10-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_remove_data_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='user',
            new_name='file',
        ),
    ]
