# Generated by Django 2.2.4 on 2019-10-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_auto_20191015_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
