# Generated by Django 2.2.4 on 2019-10-15 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0005_auto_20191015_1317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Upload',
        ),
    ]
